/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IIPRegistry,
  IIPRegistryInterface,
} from "../../../contracts/interfaces/IIPRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "taskId",
        type: "bytes32",
      },
    ],
    name: "hasIPRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IIPRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IIPRegistryInterface {
    return new Interface(_abi) as IIPRegistryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IIPRegistry {
    return new Contract(address, _abi, runner) as unknown as IIPRegistry;
  }
}
