/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWorkspaceRegistry,
  IWorkspaceRegistryInterface,
} from "../../../contracts/interfaces/IWorkspaceRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "workspaceId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
    ],
    name: "getMember",
    outputs: [
      {
        internalType: "address",
        name: "memberAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "joinedAt",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "role",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "exists",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "workspaceId",
        type: "bytes32",
      },
    ],
    name: "getWorkspace",
    outputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "description",
        type: "string",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "createdAt",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isPublic",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "memberCount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "workspaceId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isMember",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IWorkspaceRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IWorkspaceRegistryInterface {
    return new Interface(_abi) as IWorkspaceRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWorkspaceRegistry {
    return new Contract(address, _abi, runner) as unknown as IWorkspaceRegistry;
  }
}
