/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgreementRegistry {
  export type AgreementStruct = {
    id: BigNumberish;
    workspaceId: BytesLike;
    documentHash: BytesLike;
    title: string;
    agreementType: BigNumberish;
    creator: AddressLike;
    expiresAt: BigNumberish;
    required: boolean;
    createdAt: BigNumberish;
  };

  export type AgreementStructOutput = [
    id: bigint,
    workspaceId: string,
    documentHash: string,
    title: string,
    agreementType: bigint,
    creator: string,
    expiresAt: bigint,
    required: boolean,
    createdAt: bigint
  ] & {
    id: bigint;
    workspaceId: string;
    documentHash: string;
    title: string;
    agreementType: bigint;
    creator: string;
    expiresAt: bigint;
    required: boolean;
    createdAt: bigint;
  };
}

export interface AgreementRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createAgreement"
      | "getAgreement"
      | "getAgreements"
      | "getSignatures"
      | "hasSigned"
      | "hasSignedRequired"
      | "signAgreement"
      | "workspaceRegistry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AgreementCreated" | "AgreementSigned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createAgreement",
    values: [BytesLike, BytesLike, string, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgreement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgreements",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSignatures",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSigned",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSignedRequired",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signAgreement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "workspaceRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgreements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasSigned", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasSignedRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "workspaceRegistry",
    data: BytesLike
  ): Result;
}

export namespace AgreementCreatedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    workspaceId: BytesLike,
    documentHash: BytesLike
  ];
  export type OutputTuple = [
    agreementId: bigint,
    workspaceId: string,
    documentHash: string
  ];
  export interface OutputObject {
    agreementId: bigint;
    workspaceId: string;
    documentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgreementSignedEvent {
  export type InputTuple = [agreementId: BigNumberish, signer: AddressLike];
  export type OutputTuple = [agreementId: bigint, signer: string];
  export interface OutputObject {
    agreementId: bigint;
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgreementRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgreementRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgreementRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createAgreement: TypedContractMethod<
    [
      workspaceId: BytesLike,
      documentHash: BytesLike,
      title: string,
      agreementType: BigNumberish,
      expiresAt: BigNumberish,
      required: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  getAgreement: TypedContractMethod<
    [agreementId: BigNumberish],
    [AgreementRegistry.AgreementStructOutput],
    "view"
  >;

  getAgreements: TypedContractMethod<
    [workspaceId: BytesLike],
    [bigint[]],
    "view"
  >;

  getSignatures: TypedContractMethod<
    [agreementId: BigNumberish],
    [string[]],
    "view"
  >;

  hasSigned: TypedContractMethod<
    [agreementId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  hasSignedRequired: TypedContractMethod<
    [workspaceId: BytesLike, user: AddressLike],
    [boolean],
    "view"
  >;

  signAgreement: TypedContractMethod<
    [agreementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  workspaceRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createAgreement"
  ): TypedContractMethod<
    [
      workspaceId: BytesLike,
      documentHash: BytesLike,
      title: string,
      agreementType: BigNumberish,
      expiresAt: BigNumberish,
      required: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAgreement"
  ): TypedContractMethod<
    [agreementId: BigNumberish],
    [AgreementRegistry.AgreementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgreements"
  ): TypedContractMethod<[workspaceId: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getSignatures"
  ): TypedContractMethod<[agreementId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasSigned"
  ): TypedContractMethod<
    [agreementId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasSignedRequired"
  ): TypedContractMethod<
    [workspaceId: BytesLike, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "signAgreement"
  ): TypedContractMethod<[agreementId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "workspaceRegistry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AgreementCreated"
  ): TypedContractEvent<
    AgreementCreatedEvent.InputTuple,
    AgreementCreatedEvent.OutputTuple,
    AgreementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AgreementSigned"
  ): TypedContractEvent<
    AgreementSignedEvent.InputTuple,
    AgreementSignedEvent.OutputTuple,
    AgreementSignedEvent.OutputObject
  >;

  filters: {
    "AgreementCreated(uint256,bytes32,bytes32)": TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;
    AgreementCreated: TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;

    "AgreementSigned(uint256,address)": TypedContractEvent<
      AgreementSignedEvent.InputTuple,
      AgreementSignedEvent.OutputTuple,
      AgreementSignedEvent.OutputObject
    >;
    AgreementSigned: TypedContractEvent<
      AgreementSignedEvent.InputTuple,
      AgreementSignedEvent.OutputTuple,
      AgreementSignedEvent.OutputObject
    >;
  };
}
