/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NodeRegistry } from "./NodeRegistry";
export type { OTT } from "./OTT";
export type { TaskEscrow } from "./TaskEscrow";
export type { WorkspaceRegistry } from "./WorkspaceRegistry";
