/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IPRegistry {
  export type IPRegistrationStruct = {
    id: BigNumberish;
    workspaceId: BytesLike;
    taskId: BytesLike;
    creator: AddressLike;
    licenseType: BigNumberish;
    licenseCid: string;
    createdAt: BigNumberish;
  };

  export type IPRegistrationStructOutput = [
    id: bigint,
    workspaceId: string,
    taskId: string,
    creator: string,
    licenseType: bigint,
    licenseCid: string,
    createdAt: bigint
  ] & {
    id: bigint;
    workspaceId: string;
    taskId: string;
    creator: string;
    licenseType: bigint;
    licenseCid: string;
    createdAt: bigint;
  };
}

export interface IPRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getIPForTask"
      | "getRegistration"
      | "getWorkspaceIP"
      | "hasIPRegistered"
      | "registerIP"
      | "workspaceRegistry"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "IPRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "getIPForTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkspaceIP",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasIPRegistered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerIP",
    values: [BytesLike, BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "workspaceRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getIPForTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkspaceIP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasIPRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registerIP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "workspaceRegistry",
    data: BytesLike
  ): Result;
}

export namespace IPRegisteredEvent {
  export type InputTuple = [
    registrationId: BigNumberish,
    workspaceId: BytesLike,
    taskId: BytesLike,
    creator: AddressLike
  ];
  export type OutputTuple = [
    registrationId: bigint,
    workspaceId: string,
    taskId: string,
    creator: string
  ];
  export interface OutputObject {
    registrationId: bigint;
    workspaceId: string;
    taskId: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IPRegistry;
  waitForDeployment(): Promise<this>;

  interface: IPRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getIPForTask: TypedContractMethod<
    [taskId: BytesLike],
    [IPRegistry.IPRegistrationStructOutput],
    "view"
  >;

  getRegistration: TypedContractMethod<
    [registrationId: BigNumberish],
    [IPRegistry.IPRegistrationStructOutput],
    "view"
  >;

  getWorkspaceIP: TypedContractMethod<
    [workspaceId: BytesLike],
    [bigint[]],
    "view"
  >;

  hasIPRegistered: TypedContractMethod<[taskId: BytesLike], [boolean], "view">;

  registerIP: TypedContractMethod<
    [
      workspaceId: BytesLike,
      taskId: BytesLike,
      licenseType: BigNumberish,
      licenseCid: string
    ],
    [bigint],
    "nonpayable"
  >;

  workspaceRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getIPForTask"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [IPRegistry.IPRegistrationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRegistration"
  ): TypedContractMethod<
    [registrationId: BigNumberish],
    [IPRegistry.IPRegistrationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWorkspaceIP"
  ): TypedContractMethod<[workspaceId: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasIPRegistered"
  ): TypedContractMethod<[taskId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerIP"
  ): TypedContractMethod<
    [
      workspaceId: BytesLike,
      taskId: BytesLike,
      licenseType: BigNumberish,
      licenseCid: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "workspaceRegistry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "IPRegistered"
  ): TypedContractEvent<
    IPRegisteredEvent.InputTuple,
    IPRegisteredEvent.OutputTuple,
    IPRegisteredEvent.OutputObject
  >;

  filters: {
    "IPRegistered(uint256,bytes32,bytes32,address)": TypedContractEvent<
      IPRegisteredEvent.InputTuple,
      IPRegisteredEvent.OutputTuple,
      IPRegisteredEvent.OutputObject
    >;
    IPRegistered: TypedContractEvent<
      IPRegisteredEvent.InputTuple,
      IPRegisteredEvent.OutputTuple,
      IPRegisteredEvent.OutputObject
    >;
  };
}
