/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MilestoneEscrow {
  export type MilestoneStruct = {
    description: string;
    amount: BigNumberish;
    status: BigNumberish;
    workCid: string;
    submittedAt: BigNumberish;
    approvedAt: BigNumberish;
  };

  export type MilestoneStructOutput = [
    description: string,
    amount: bigint,
    status: bigint,
    workCid: string,
    submittedAt: bigint,
    approvedAt: bigint
  ] & {
    description: string;
    amount: bigint;
    status: bigint;
    workCid: string;
    submittedAt: bigint;
    approvedAt: bigint;
  };

  export type TaskStruct = {
    id: BytesLike;
    creator: AddressLike;
    worker: AddressLike;
    workspaceId: BytesLike;
    descriptionCid: string;
    deadline: BigNumberish;
    status: BigNumberish;
    totalAmount: BigNumberish;
    platformFee: BigNumberish;
    milestoneCount: BigNumberish;
    createdAt: BigNumberish;
  };

  export type TaskStructOutput = [
    id: string,
    creator: string,
    worker: string,
    workspaceId: string,
    descriptionCid: string,
    deadline: bigint,
    status: bigint,
    totalAmount: bigint,
    platformFee: bigint,
    milestoneCount: bigint,
    createdAt: bigint
  ] & {
    id: string;
    creator: string;
    worker: string;
    workspaceId: string;
    descriptionCid: string;
    deadline: bigint;
    status: bigint;
    totalAmount: bigint;
    platformFee: bigint;
    milestoneCount: bigint;
    createdAt: bigint;
  };
}

export interface MilestoneEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISPUTE_WINDOW"
      | "agreementRegistry"
      | "approveMilestone"
      | "assignWorker"
      | "cancelTask"
      | "createTask"
      | "disputeMilestone"
      | "feeRecipient"
      | "getCreatorTasks"
      | "getMilestones"
      | "getTask"
      | "getWorkerTasks"
      | "ipRegistry"
      | "nodeRegistry"
      | "ottToken"
      | "owner"
      | "platformFeePercent"
      | "releaseMilestonePayment"
      | "renounceOwnership"
      | "setFeeRecipient"
      | "setPlatformFeePercent"
      | "submitMilestone"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MilestoneApproved"
      | "MilestoneDisputed"
      | "MilestonePaymentReleased"
      | "MilestoneSubmitted"
      | "OwnershipTransferred"
      | "TaskCancelled"
      | "TaskCreated"
      | "WorkerAssigned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISPUTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agreementRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveMilestone",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignWorker",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [BytesLike, string, BigNumberish, string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeMilestone",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorTasks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestones",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getTask", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getWorkerTasks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ipRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nodeRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ottToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releaseMilestonePayment",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitMilestone",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DISPUTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agreementRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignWorker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWorkerTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ipRegistry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nodeRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ottToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseMilestonePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MilestoneApprovedEvent {
  export type InputTuple = [taskId: BytesLike, milestoneIndex: BigNumberish];
  export type OutputTuple = [taskId: string, milestoneIndex: bigint];
  export interface OutputObject {
    taskId: string;
    milestoneIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneDisputedEvent {
  export type InputTuple = [taskId: BytesLike, milestoneIndex: BigNumberish];
  export type OutputTuple = [taskId: string, milestoneIndex: bigint];
  export interface OutputObject {
    taskId: string;
    milestoneIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestonePaymentReleasedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    milestoneIndex: BigNumberish,
    worker: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    milestoneIndex: bigint,
    worker: string,
    amount: bigint
  ];
  export interface OutputObject {
    taskId: string;
    milestoneIndex: bigint;
    worker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneSubmittedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    milestoneIndex: BigNumberish,
    workCid: string
  ];
  export type OutputTuple = [
    taskId: string,
    milestoneIndex: bigint,
    workCid: string
  ];
  export interface OutputObject {
    taskId: string;
    milestoneIndex: bigint;
    workCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [taskId: BytesLike, refundAmount: BigNumberish];
  export type OutputTuple = [taskId: string, refundAmount: bigint];
  export interface OutputObject {
    taskId: string;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    workspaceId: BytesLike,
    creator: AddressLike,
    totalAmount: BigNumberish,
    milestoneCount: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    workspaceId: string,
    creator: string,
    totalAmount: bigint,
    milestoneCount: bigint
  ];
  export interface OutputObject {
    taskId: string;
    workspaceId: string;
    creator: string;
    totalAmount: bigint;
    milestoneCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkerAssignedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    worker: AddressLike,
    nodeId: BytesLike
  ];
  export type OutputTuple = [taskId: string, worker: string, nodeId: string];
  export interface OutputObject {
    taskId: string;
    worker: string;
    nodeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MilestoneEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): MilestoneEscrow;
  waitForDeployment(): Promise<this>;

  interface: MilestoneEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISPUTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  agreementRegistry: TypedContractMethod<[], [string], "view">;

  approveMilestone: TypedContractMethod<
    [taskId: BytesLike, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  assignWorker: TypedContractMethod<
    [taskId: BytesLike, workerAddress: AddressLike, nodeId: BytesLike],
    [void],
    "nonpayable"
  >;

  cancelTask: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  createTask: TypedContractMethod<
    [
      workspaceId: BytesLike,
      descriptionCid: string,
      deadline: BigNumberish,
      milestoneDescriptions: string[],
      milestoneAmounts: BigNumberish[]
    ],
    [string],
    "nonpayable"
  >;

  disputeMilestone: TypedContractMethod<
    [taskId: BytesLike, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getCreatorTasks: TypedContractMethod<
    [creator: AddressLike],
    [string[]],
    "view"
  >;

  getMilestones: TypedContractMethod<
    [taskId: BytesLike],
    [MilestoneEscrow.MilestoneStructOutput[]],
    "view"
  >;

  getTask: TypedContractMethod<
    [taskId: BytesLike],
    [MilestoneEscrow.TaskStructOutput],
    "view"
  >;

  getWorkerTasks: TypedContractMethod<
    [worker: AddressLike],
    [string[]],
    "view"
  >;

  ipRegistry: TypedContractMethod<[], [string], "view">;

  nodeRegistry: TypedContractMethod<[], [string], "view">;

  ottToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  releaseMilestonePayment: TypedContractMethod<
    [taskId: BytesLike, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFeeRecipient: TypedContractMethod<
    [_feeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFeePercent: TypedContractMethod<
    [_percent: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitMilestone: TypedContractMethod<
    [taskId: BytesLike, milestoneIndex: BigNumberish, workCid: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISPUTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agreementRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveMilestone"
  ): TypedContractMethod<
    [taskId: BytesLike, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assignWorker"
  ): TypedContractMethod<
    [taskId: BytesLike, workerAddress: AddressLike, nodeId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [
      workspaceId: BytesLike,
      descriptionCid: string,
      deadline: BigNumberish,
      milestoneDescriptions: string[],
      milestoneAmounts: BigNumberish[]
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeMilestone"
  ): TypedContractMethod<
    [taskId: BytesLike, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCreatorTasks"
  ): TypedContractMethod<[creator: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMilestones"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [MilestoneEscrow.MilestoneStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [MilestoneEscrow.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWorkerTasks"
  ): TypedContractMethod<[worker: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "ipRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nodeRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ottToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "releaseMilestonePayment"
  ): TypedContractMethod<
    [taskId: BytesLike, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[_feeRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFeePercent"
  ): TypedContractMethod<[_percent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitMilestone"
  ): TypedContractMethod<
    [taskId: BytesLike, milestoneIndex: BigNumberish, workCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MilestoneApproved"
  ): TypedContractEvent<
    MilestoneApprovedEvent.InputTuple,
    MilestoneApprovedEvent.OutputTuple,
    MilestoneApprovedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneDisputed"
  ): TypedContractEvent<
    MilestoneDisputedEvent.InputTuple,
    MilestoneDisputedEvent.OutputTuple,
    MilestoneDisputedEvent.OutputObject
  >;
  getEvent(
    key: "MilestonePaymentReleased"
  ): TypedContractEvent<
    MilestonePaymentReleasedEvent.InputTuple,
    MilestonePaymentReleasedEvent.OutputTuple,
    MilestonePaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneSubmitted"
  ): TypedContractEvent<
    MilestoneSubmittedEvent.InputTuple,
    MilestoneSubmittedEvent.OutputTuple,
    MilestoneSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "WorkerAssigned"
  ): TypedContractEvent<
    WorkerAssignedEvent.InputTuple,
    WorkerAssignedEvent.OutputTuple,
    WorkerAssignedEvent.OutputObject
  >;

  filters: {
    "MilestoneApproved(bytes32,uint256)": TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;
    MilestoneApproved: TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;

    "MilestoneDisputed(bytes32,uint256)": TypedContractEvent<
      MilestoneDisputedEvent.InputTuple,
      MilestoneDisputedEvent.OutputTuple,
      MilestoneDisputedEvent.OutputObject
    >;
    MilestoneDisputed: TypedContractEvent<
      MilestoneDisputedEvent.InputTuple,
      MilestoneDisputedEvent.OutputTuple,
      MilestoneDisputedEvent.OutputObject
    >;

    "MilestonePaymentReleased(bytes32,uint256,address,uint256)": TypedContractEvent<
      MilestonePaymentReleasedEvent.InputTuple,
      MilestonePaymentReleasedEvent.OutputTuple,
      MilestonePaymentReleasedEvent.OutputObject
    >;
    MilestonePaymentReleased: TypedContractEvent<
      MilestonePaymentReleasedEvent.InputTuple,
      MilestonePaymentReleasedEvent.OutputTuple,
      MilestonePaymentReleasedEvent.OutputObject
    >;

    "MilestoneSubmitted(bytes32,uint256,string)": TypedContractEvent<
      MilestoneSubmittedEvent.InputTuple,
      MilestoneSubmittedEvent.OutputTuple,
      MilestoneSubmittedEvent.OutputObject
    >;
    MilestoneSubmitted: TypedContractEvent<
      MilestoneSubmittedEvent.InputTuple,
      MilestoneSubmittedEvent.OutputTuple,
      MilestoneSubmittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TaskCancelled(bytes32,uint256)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskCreated(bytes32,bytes32,address,uint256,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "WorkerAssigned(bytes32,address,bytes32)": TypedContractEvent<
      WorkerAssignedEvent.InputTuple,
      WorkerAssignedEvent.OutputTuple,
      WorkerAssignedEvent.OutputObject
    >;
    WorkerAssigned: TypedContractEvent<
      WorkerAssignedEvent.InputTuple,
      WorkerAssignedEvent.OutputTuple,
      WorkerAssignedEvent.OutputObject
    >;
  };
}
