/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace NodeRegistry {
  export type CapabilitiesStruct = {
    cpuCores: BigNumberish;
    memoryMb: BigNumberish;
    gpuCount: BigNumberish;
    gpuVramMb: BigNumberish;
    hasOllama: boolean;
    hasSandbox: boolean;
  };

  export type CapabilitiesStructOutput = [
    cpuCores: bigint,
    memoryMb: bigint,
    gpuCount: bigint,
    gpuVramMb: bigint,
    hasOllama: boolean,
    hasSandbox: boolean
  ] & {
    cpuCores: bigint;
    memoryMb: bigint;
    gpuCount: bigint;
    gpuVramMb: bigint;
    hasOllama: boolean;
    hasSandbox: boolean;
  };

  export type NodeStruct = {
    owner: AddressLike;
    stakedAmount: BigNumberish;
    pendingRewards: BigNumberish;
    totalEarned: BigNumberish;
    totalComputeSeconds: BigNumberish;
    reputation: BigNumberish;
    registeredAt: BigNumberish;
    lastActiveAt: BigNumberish;
    isActive: boolean;
    isSlashed: boolean;
    capabilities: NodeRegistry.CapabilitiesStruct;
    endpoint: string;
  };

  export type NodeStructOutput = [
    owner: string,
    stakedAmount: bigint,
    pendingRewards: bigint,
    totalEarned: bigint,
    totalComputeSeconds: bigint,
    reputation: bigint,
    registeredAt: bigint,
    lastActiveAt: bigint,
    isActive: boolean,
    isSlashed: boolean,
    capabilities: NodeRegistry.CapabilitiesStructOutput,
    endpoint: string
  ] & {
    owner: string;
    stakedAmount: bigint;
    pendingRewards: bigint;
    totalEarned: bigint;
    totalComputeSeconds: bigint;
    reputation: bigint;
    registeredAt: bigint;
    lastActiveAt: bigint;
    isActive: boolean;
    isSlashed: boolean;
    capabilities: NodeRegistry.CapabilitiesStructOutput;
    endpoint: string;
  };
}

export interface NodeRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addReporter"
      | "addStake"
      | "allNodeIds"
      | "authorizedReporters"
      | "claimRewards"
      | "deactivateNode"
      | "getNode"
      | "getOwnerNodes"
      | "getTotalNodes"
      | "isNodeEligible"
      | "minStake"
      | "ottToken"
      | "owner"
      | "ownerNodes"
      | "reactivateNode"
      | "registerNode"
      | "removeReporter"
      | "renounceOwnership"
      | "reportCompute"
      | "rewardRate"
      | "setMinStake"
      | "setRewardRate"
      | "transferOwnership"
      | "updateCapabilities"
      | "updateEndpoint"
      | "withdrawStake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComputeReported"
      | "NodeDeactivated"
      | "NodeReactivated"
      | "NodeRegistered"
      | "OwnershipTransferred"
      | "ReporterAdded"
      | "ReporterRemoved"
      | "RewardsClaimed"
      | "StakeAdded"
      | "StakeWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addReporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addStake",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allNodeIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedReporters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateNode",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getNode", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getOwnerNodes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalNodes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isNodeEligible",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "minStake", values?: undefined): string;
  encodeFunctionData(functionFragment: "ottToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerNodes",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateNode",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerNode",
    values: [NodeRegistry.CapabilitiesStruct, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeReporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reportCompute",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMinStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCapabilities",
    values: [BytesLike, NodeRegistry.CapabilitiesStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEndpoint",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStake",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addReporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addStake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allNodeIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedReporters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerNodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalNodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isNodeEligible",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minStake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ottToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerNodes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeReporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportCompute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rewardRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCapabilities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEndpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStake",
    data: BytesLike
  ): Result;
}

export namespace ComputeReportedEvent {
  export type InputTuple = [
    nodeId: BytesLike,
    seconds_: BigNumberish,
    reward: BigNumberish
  ];
  export type OutputTuple = [nodeId: string, seconds_: bigint, reward: bigint];
  export interface OutputObject {
    nodeId: string;
    seconds_: bigint;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeDeactivatedEvent {
  export type InputTuple = [nodeId: BytesLike];
  export type OutputTuple = [nodeId: string];
  export interface OutputObject {
    nodeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeReactivatedEvent {
  export type InputTuple = [nodeId: BytesLike];
  export type OutputTuple = [nodeId: string];
  export interface OutputObject {
    nodeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeRegisteredEvent {
  export type InputTuple = [
    nodeId: BytesLike,
    owner: AddressLike,
    stake: BigNumberish
  ];
  export type OutputTuple = [nodeId: string, owner: string, stake: bigint];
  export interface OutputObject {
    nodeId: string;
    owner: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReporterAddedEvent {
  export type InputTuple = [reporter: AddressLike];
  export type OutputTuple = [reporter: string];
  export interface OutputObject {
    reporter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReporterRemovedEvent {
  export type InputTuple = [reporter: AddressLike];
  export type OutputTuple = [reporter: string];
  export interface OutputObject {
    reporter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [
    nodeId: BytesLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [nodeId: string, to: string, amount: bigint];
  export interface OutputObject {
    nodeId: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeAddedEvent {
  export type InputTuple = [nodeId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [nodeId: string, amount: bigint];
  export interface OutputObject {
    nodeId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeWithdrawnEvent {
  export type InputTuple = [nodeId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [nodeId: string, amount: bigint];
  export interface OutputObject {
    nodeId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NodeRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): NodeRegistry;
  waitForDeployment(): Promise<this>;

  interface: NodeRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addReporter: TypedContractMethod<
    [reporter: AddressLike],
    [void],
    "nonpayable"
  >;

  addStake: TypedContractMethod<
    [nodeId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  allNodeIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  authorizedReporters: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  claimRewards: TypedContractMethod<[nodeId: BytesLike], [void], "nonpayable">;

  deactivateNode: TypedContractMethod<
    [nodeId: BytesLike],
    [void],
    "nonpayable"
  >;

  getNode: TypedContractMethod<
    [nodeId: BytesLike],
    [NodeRegistry.NodeStructOutput],
    "view"
  >;

  getOwnerNodes: TypedContractMethod<[owner_: AddressLike], [string[]], "view">;

  getTotalNodes: TypedContractMethod<[], [bigint], "view">;

  isNodeEligible: TypedContractMethod<[nodeId: BytesLike], [boolean], "view">;

  minStake: TypedContractMethod<[], [bigint], "view">;

  ottToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerNodes: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  reactivateNode: TypedContractMethod<
    [nodeId: BytesLike],
    [void],
    "nonpayable"
  >;

  registerNode: TypedContractMethod<
    [
      capabilities: NodeRegistry.CapabilitiesStruct,
      endpoint: string,
      stakeAmount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  removeReporter: TypedContractMethod<
    [reporter: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reportCompute: TypedContractMethod<
    [nodeId: BytesLike, computeSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  rewardRate: TypedContractMethod<[], [bigint], "view">;

  setMinStake: TypedContractMethod<
    [_minStake: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRewardRate: TypedContractMethod<
    [_rewardRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCapabilities: TypedContractMethod<
    [nodeId: BytesLike, capabilities: NodeRegistry.CapabilitiesStruct],
    [void],
    "nonpayable"
  >;

  updateEndpoint: TypedContractMethod<
    [nodeId: BytesLike, endpoint: string],
    [void],
    "nonpayable"
  >;

  withdrawStake: TypedContractMethod<
    [nodeId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addReporter"
  ): TypedContractMethod<[reporter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addStake"
  ): TypedContractMethod<
    [nodeId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allNodeIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "authorizedReporters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[nodeId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateNode"
  ): TypedContractMethod<[nodeId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getNode"
  ): TypedContractMethod<
    [nodeId: BytesLike],
    [NodeRegistry.NodeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnerNodes"
  ): TypedContractMethod<[owner_: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalNodes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isNodeEligible"
  ): TypedContractMethod<[nodeId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "minStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ottToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerNodes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "reactivateNode"
  ): TypedContractMethod<[nodeId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerNode"
  ): TypedContractMethod<
    [
      capabilities: NodeRegistry.CapabilitiesStruct,
      endpoint: string,
      stakeAmount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeReporter"
  ): TypedContractMethod<[reporter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reportCompute"
  ): TypedContractMethod<
    [nodeId: BytesLike, computeSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rewardRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setMinStake"
  ): TypedContractMethod<[_minStake: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRewardRate"
  ): TypedContractMethod<[_rewardRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCapabilities"
  ): TypedContractMethod<
    [nodeId: BytesLike, capabilities: NodeRegistry.CapabilitiesStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateEndpoint"
  ): TypedContractMethod<
    [nodeId: BytesLike, endpoint: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawStake"
  ): TypedContractMethod<
    [nodeId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ComputeReported"
  ): TypedContractEvent<
    ComputeReportedEvent.InputTuple,
    ComputeReportedEvent.OutputTuple,
    ComputeReportedEvent.OutputObject
  >;
  getEvent(
    key: "NodeDeactivated"
  ): TypedContractEvent<
    NodeDeactivatedEvent.InputTuple,
    NodeDeactivatedEvent.OutputTuple,
    NodeDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "NodeReactivated"
  ): TypedContractEvent<
    NodeReactivatedEvent.InputTuple,
    NodeReactivatedEvent.OutputTuple,
    NodeReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "NodeRegistered"
  ): TypedContractEvent<
    NodeRegisteredEvent.InputTuple,
    NodeRegisteredEvent.OutputTuple,
    NodeRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReporterAdded"
  ): TypedContractEvent<
    ReporterAddedEvent.InputTuple,
    ReporterAddedEvent.OutputTuple,
    ReporterAddedEvent.OutputObject
  >;
  getEvent(
    key: "ReporterRemoved"
  ): TypedContractEvent<
    ReporterRemovedEvent.InputTuple,
    ReporterRemovedEvent.OutputTuple,
    ReporterRemovedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "StakeAdded"
  ): TypedContractEvent<
    StakeAddedEvent.InputTuple,
    StakeAddedEvent.OutputTuple,
    StakeAddedEvent.OutputObject
  >;
  getEvent(
    key: "StakeWithdrawn"
  ): TypedContractEvent<
    StakeWithdrawnEvent.InputTuple,
    StakeWithdrawnEvent.OutputTuple,
    StakeWithdrawnEvent.OutputObject
  >;

  filters: {
    "ComputeReported(bytes32,uint256,uint256)": TypedContractEvent<
      ComputeReportedEvent.InputTuple,
      ComputeReportedEvent.OutputTuple,
      ComputeReportedEvent.OutputObject
    >;
    ComputeReported: TypedContractEvent<
      ComputeReportedEvent.InputTuple,
      ComputeReportedEvent.OutputTuple,
      ComputeReportedEvent.OutputObject
    >;

    "NodeDeactivated(bytes32)": TypedContractEvent<
      NodeDeactivatedEvent.InputTuple,
      NodeDeactivatedEvent.OutputTuple,
      NodeDeactivatedEvent.OutputObject
    >;
    NodeDeactivated: TypedContractEvent<
      NodeDeactivatedEvent.InputTuple,
      NodeDeactivatedEvent.OutputTuple,
      NodeDeactivatedEvent.OutputObject
    >;

    "NodeReactivated(bytes32)": TypedContractEvent<
      NodeReactivatedEvent.InputTuple,
      NodeReactivatedEvent.OutputTuple,
      NodeReactivatedEvent.OutputObject
    >;
    NodeReactivated: TypedContractEvent<
      NodeReactivatedEvent.InputTuple,
      NodeReactivatedEvent.OutputTuple,
      NodeReactivatedEvent.OutputObject
    >;

    "NodeRegistered(bytes32,address,uint256)": TypedContractEvent<
      NodeRegisteredEvent.InputTuple,
      NodeRegisteredEvent.OutputTuple,
      NodeRegisteredEvent.OutputObject
    >;
    NodeRegistered: TypedContractEvent<
      NodeRegisteredEvent.InputTuple,
      NodeRegisteredEvent.OutputTuple,
      NodeRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReporterAdded(address)": TypedContractEvent<
      ReporterAddedEvent.InputTuple,
      ReporterAddedEvent.OutputTuple,
      ReporterAddedEvent.OutputObject
    >;
    ReporterAdded: TypedContractEvent<
      ReporterAddedEvent.InputTuple,
      ReporterAddedEvent.OutputTuple,
      ReporterAddedEvent.OutputObject
    >;

    "ReporterRemoved(address)": TypedContractEvent<
      ReporterRemovedEvent.InputTuple,
      ReporterRemovedEvent.OutputTuple,
      ReporterRemovedEvent.OutputObject
    >;
    ReporterRemoved: TypedContractEvent<
      ReporterRemovedEvent.InputTuple,
      ReporterRemovedEvent.OutputTuple,
      ReporterRemovedEvent.OutputObject
    >;

    "RewardsClaimed(bytes32,address,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;

    "StakeAdded(bytes32,uint256)": TypedContractEvent<
      StakeAddedEvent.InputTuple,
      StakeAddedEvent.OutputTuple,
      StakeAddedEvent.OutputObject
    >;
    StakeAdded: TypedContractEvent<
      StakeAddedEvent.InputTuple,
      StakeAddedEvent.OutputTuple,
      StakeAddedEvent.OutputObject
    >;

    "StakeWithdrawn(bytes32,uint256)": TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;
    StakeWithdrawn: TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;
  };
}
