/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface OTTTreasuryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DECIMAL_OFFSET"
      | "MAX_REDEMPTION_FEE_BPS"
      | "buyOTT"
      | "circulatingTreasuryOTT"
      | "depositFees"
      | "getBackingPerOTT"
      | "getRedeemAmount"
      | "ottToken"
      | "owner"
      | "pause"
      | "paused"
      | "redeemOTT"
      | "redemptionFeeBps"
      | "renounceOwnership"
      | "setRedemptionFee"
      | "transferOwnership"
      | "unpause"
      | "usdcToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeesDeposited"
      | "OTTBought"
      | "OTTRedeemed"
      | "OwnershipTransferred"
      | "Paused"
      | "RedemptionFeeUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DECIMAL_OFFSET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_REDEMPTION_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyOTT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "circulatingTreasuryOTT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBackingPerOTT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRedeemAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ottToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeemOTT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redemptionFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRedemptionFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DECIMAL_OFFSET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_REDEMPTION_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyOTT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "circulatingTreasuryOTT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBackingPerOTT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRedeemAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ottToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeemOTT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redemptionFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRedemptionFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
}

export namespace FeesDepositedEvent {
  export type InputTuple = [depositor: AddressLike, usdcAmount: BigNumberish];
  export type OutputTuple = [depositor: string, usdcAmount: bigint];
  export interface OutputObject {
    depositor: string;
    usdcAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OTTBoughtEvent {
  export type InputTuple = [
    buyer: AddressLike,
    usdcAmount: BigNumberish,
    ottAmount: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    usdcAmount: bigint,
    ottAmount: bigint
  ];
  export interface OutputObject {
    buyer: string;
    usdcAmount: bigint;
    ottAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OTTRedeemedEvent {
  export type InputTuple = [
    redeemer: AddressLike,
    ottAmount: BigNumberish,
    usdcAmount: BigNumberish
  ];
  export type OutputTuple = [
    redeemer: string,
    ottAmount: bigint,
    usdcAmount: bigint
  ];
  export interface OutputObject {
    redeemer: string;
    ottAmount: bigint;
    usdcAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionFeeUpdatedEvent {
  export type InputTuple = [oldFeeBps: BigNumberish, newFeeBps: BigNumberish];
  export type OutputTuple = [oldFeeBps: bigint, newFeeBps: bigint];
  export interface OutputObject {
    oldFeeBps: bigint;
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OTTTreasury extends BaseContract {
  connect(runner?: ContractRunner | null): OTTTreasury;
  waitForDeployment(): Promise<this>;

  interface: OTTTreasuryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DECIMAL_OFFSET: TypedContractMethod<[], [bigint], "view">;

  MAX_REDEMPTION_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  buyOTT: TypedContractMethod<[usdcAmount: BigNumberish], [void], "nonpayable">;

  circulatingTreasuryOTT: TypedContractMethod<[], [bigint], "view">;

  depositFees: TypedContractMethod<
    [usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBackingPerOTT: TypedContractMethod<[], [bigint], "view">;

  getRedeemAmount: TypedContractMethod<
    [ottAmount: BigNumberish],
    [bigint],
    "view"
  >;

  ottToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  redeemOTT: TypedContractMethod<
    [ottAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  redemptionFeeBps: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setRedemptionFee: TypedContractMethod<
    [bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usdcToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DECIMAL_OFFSET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_REDEMPTION_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyOTT"
  ): TypedContractMethod<[usdcAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "circulatingTreasuryOTT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositFees"
  ): TypedContractMethod<[usdcAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBackingPerOTT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRedeemAmount"
  ): TypedContractMethod<[ottAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "ottToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "redeemOTT"
  ): TypedContractMethod<[ottAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "redemptionFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRedemptionFee"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FeesDeposited"
  ): TypedContractEvent<
    FeesDepositedEvent.InputTuple,
    FeesDepositedEvent.OutputTuple,
    FeesDepositedEvent.OutputObject
  >;
  getEvent(
    key: "OTTBought"
  ): TypedContractEvent<
    OTTBoughtEvent.InputTuple,
    OTTBoughtEvent.OutputTuple,
    OTTBoughtEvent.OutputObject
  >;
  getEvent(
    key: "OTTRedeemed"
  ): TypedContractEvent<
    OTTRedeemedEvent.InputTuple,
    OTTRedeemedEvent.OutputTuple,
    OTTRedeemedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionFeeUpdated"
  ): TypedContractEvent<
    RedemptionFeeUpdatedEvent.InputTuple,
    RedemptionFeeUpdatedEvent.OutputTuple,
    RedemptionFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "FeesDeposited(address,uint256)": TypedContractEvent<
      FeesDepositedEvent.InputTuple,
      FeesDepositedEvent.OutputTuple,
      FeesDepositedEvent.OutputObject
    >;
    FeesDeposited: TypedContractEvent<
      FeesDepositedEvent.InputTuple,
      FeesDepositedEvent.OutputTuple,
      FeesDepositedEvent.OutputObject
    >;

    "OTTBought(address,uint256,uint256)": TypedContractEvent<
      OTTBoughtEvent.InputTuple,
      OTTBoughtEvent.OutputTuple,
      OTTBoughtEvent.OutputObject
    >;
    OTTBought: TypedContractEvent<
      OTTBoughtEvent.InputTuple,
      OTTBoughtEvent.OutputTuple,
      OTTBoughtEvent.OutputObject
    >;

    "OTTRedeemed(address,uint256,uint256)": TypedContractEvent<
      OTTRedeemedEvent.InputTuple,
      OTTRedeemedEvent.OutputTuple,
      OTTRedeemedEvent.OutputObject
    >;
    OTTRedeemed: TypedContractEvent<
      OTTRedeemedEvent.InputTuple,
      OTTRedeemedEvent.OutputTuple,
      OTTRedeemedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RedemptionFeeUpdated(uint256,uint256)": TypedContractEvent<
      RedemptionFeeUpdatedEvent.InputTuple,
      RedemptionFeeUpdatedEvent.OutputTuple,
      RedemptionFeeUpdatedEvent.OutputObject
    >;
    RedemptionFeeUpdated: TypedContractEvent<
      RedemptionFeeUpdatedEvent.InputTuple,
      RedemptionFeeUpdatedEvent.OutputTuple,
      RedemptionFeeUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
