/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TaskEscrow {
  export type TaskStruct = {
    requester: AddressLike;
    nodeId: BytesLike;
    amount: BigNumberish;
    platformFee: BigNumberish;
    status: BigNumberish;
    resultHash: BytesLike;
    createdAt: BigNumberish;
    completedAt: BigNumberish;
    description: string;
  };

  export type TaskStructOutput = [
    requester: string,
    nodeId: string,
    amount: bigint,
    platformFee: bigint,
    status: bigint,
    resultHash: string,
    createdAt: bigint,
    completedAt: bigint,
    description: string
  ] & {
    requester: string;
    nodeId: string;
    amount: bigint;
    platformFee: bigint;
    status: bigint;
    resultHash: string;
    createdAt: bigint;
    completedAt: bigint;
    description: string;
  };
}

export interface TaskEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addManager"
      | "allTaskIds"
      | "assignTask"
      | "cancelTask"
      | "completeTask"
      | "createTask"
      | "disputeTask"
      | "disputeTimeout"
      | "feeRecipient"
      | "getTask"
      | "getTotalTasks"
      | "managers"
      | "ottToken"
      | "owner"
      | "platformFeePercent"
      | "refundTask"
      | "releasePayment"
      | "removeManager"
      | "renounceOwnership"
      | "setDisputeTimeout"
      | "setFeeRecipient"
      | "setPlatformFeePercent"
      | "tasks"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ManagerAdded"
      | "ManagerRemoved"
      | "OwnershipTransferred"
      | "TaskAssigned"
      | "TaskCompleted"
      | "TaskCreated"
      | "TaskDisputed"
      | "TaskRefunded"
      | "TaskReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allTaskIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignTask",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeTask",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getTask", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getTotalTasks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "managers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "ottToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releasePayment",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDisputeTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addManager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allTaskIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assignTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "managers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ottToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refundTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releasePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDisputeTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ManagerAddedEvent {
  export type InputTuple = [manager: AddressLike];
  export type OutputTuple = [manager: string];
  export interface OutputObject {
    manager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagerRemovedEvent {
  export type InputTuple = [manager: AddressLike];
  export type OutputTuple = [manager: string];
  export interface OutputObject {
    manager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAssignedEvent {
  export type InputTuple = [taskId: BytesLike, nodeId: BytesLike];
  export type OutputTuple = [taskId: string, nodeId: string];
  export interface OutputObject {
    taskId: string;
    nodeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [taskId: BytesLike, resultHash: BytesLike];
  export type OutputTuple = [taskId: string, resultHash: string];
  export interface OutputObject {
    taskId: string;
    resultHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    requester: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: string, requester: string, amount: bigint];
  export interface OutputObject {
    taskId: string;
    requester: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskDisputedEvent {
  export type InputTuple = [taskId: BytesLike, disputer: AddressLike];
  export type OutputTuple = [taskId: string, disputer: string];
  export interface OutputObject {
    taskId: string;
    disputer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskRefundedEvent {
  export type InputTuple = [taskId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [taskId: string, amount: bigint];
  export interface OutputObject {
    taskId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskReleasedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    nodeOwner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: string, nodeOwner: string, amount: bigint];
  export interface OutputObject {
    taskId: string;
    nodeOwner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): TaskEscrow;
  waitForDeployment(): Promise<this>;

  interface: TaskEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addManager: TypedContractMethod<[manager: AddressLike], [void], "nonpayable">;

  allTaskIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  assignTask: TypedContractMethod<
    [taskId: BytesLike, nodeId: BytesLike],
    [void],
    "nonpayable"
  >;

  cancelTask: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  completeTask: TypedContractMethod<
    [taskId: BytesLike, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;

  createTask: TypedContractMethod<
    [taskId: BytesLike, amount: BigNumberish, description: string],
    [void],
    "nonpayable"
  >;

  disputeTask: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  disputeTimeout: TypedContractMethod<[], [bigint], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getTask: TypedContractMethod<
    [taskId: BytesLike],
    [TaskEscrow.TaskStructOutput],
    "view"
  >;

  getTotalTasks: TypedContractMethod<[], [bigint], "view">;

  managers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  ottToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  refundTask: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  releasePayment: TypedContractMethod<
    [taskId: BytesLike, nodeOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  removeManager: TypedContractMethod<
    [manager: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDisputeTimeout: TypedContractMethod<
    [_timeout: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeRecipient: TypedContractMethod<
    [_feeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFeePercent: TypedContractMethod<
    [_percent: BigNumberish],
    [void],
    "nonpayable"
  >;

  tasks: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string
      ] & {
        requester: string;
        nodeId: string;
        amount: bigint;
        platformFee: bigint;
        status: bigint;
        resultHash: string;
        createdAt: bigint;
        completedAt: bigint;
        description: string;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addManager"
  ): TypedContractMethod<[manager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allTaskIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "assignTask"
  ): TypedContractMethod<
    [taskId: BytesLike, nodeId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeTask"
  ): TypedContractMethod<
    [taskId: BytesLike, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [taskId: BytesLike, amount: BigNumberish, description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeTask"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disputeTimeout"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [TaskEscrow.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalTasks"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "managers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "ottToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "refundTask"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releasePayment"
  ): TypedContractMethod<
    [taskId: BytesLike, nodeOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeManager"
  ): TypedContractMethod<[manager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDisputeTimeout"
  ): TypedContractMethod<[_timeout: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[_feeRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFeePercent"
  ): TypedContractMethod<[_percent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string
      ] & {
        requester: string;
        nodeId: string;
        amount: bigint;
        platformFee: bigint;
        status: bigint;
        resultHash: string;
        createdAt: bigint;
        completedAt: bigint;
        description: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ManagerAdded"
  ): TypedContractEvent<
    ManagerAddedEvent.InputTuple,
    ManagerAddedEvent.OutputTuple,
    ManagerAddedEvent.OutputObject
  >;
  getEvent(
    key: "ManagerRemoved"
  ): TypedContractEvent<
    ManagerRemovedEvent.InputTuple,
    ManagerRemovedEvent.OutputTuple,
    ManagerRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TaskAssigned"
  ): TypedContractEvent<
    TaskAssignedEvent.InputTuple,
    TaskAssignedEvent.OutputTuple,
    TaskAssignedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskDisputed"
  ): TypedContractEvent<
    TaskDisputedEvent.InputTuple,
    TaskDisputedEvent.OutputTuple,
    TaskDisputedEvent.OutputObject
  >;
  getEvent(
    key: "TaskRefunded"
  ): TypedContractEvent<
    TaskRefundedEvent.InputTuple,
    TaskRefundedEvent.OutputTuple,
    TaskRefundedEvent.OutputObject
  >;
  getEvent(
    key: "TaskReleased"
  ): TypedContractEvent<
    TaskReleasedEvent.InputTuple,
    TaskReleasedEvent.OutputTuple,
    TaskReleasedEvent.OutputObject
  >;

  filters: {
    "ManagerAdded(address)": TypedContractEvent<
      ManagerAddedEvent.InputTuple,
      ManagerAddedEvent.OutputTuple,
      ManagerAddedEvent.OutputObject
    >;
    ManagerAdded: TypedContractEvent<
      ManagerAddedEvent.InputTuple,
      ManagerAddedEvent.OutputTuple,
      ManagerAddedEvent.OutputObject
    >;

    "ManagerRemoved(address)": TypedContractEvent<
      ManagerRemovedEvent.InputTuple,
      ManagerRemovedEvent.OutputTuple,
      ManagerRemovedEvent.OutputObject
    >;
    ManagerRemoved: TypedContractEvent<
      ManagerRemovedEvent.InputTuple,
      ManagerRemovedEvent.OutputTuple,
      ManagerRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TaskAssigned(bytes32,bytes32)": TypedContractEvent<
      TaskAssignedEvent.InputTuple,
      TaskAssignedEvent.OutputTuple,
      TaskAssignedEvent.OutputObject
    >;
    TaskAssigned: TypedContractEvent<
      TaskAssignedEvent.InputTuple,
      TaskAssignedEvent.OutputTuple,
      TaskAssignedEvent.OutputObject
    >;

    "TaskCompleted(bytes32,bytes32)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;

    "TaskCreated(bytes32,address,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskDisputed(bytes32,address)": TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;
    TaskDisputed: TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;

    "TaskRefunded(bytes32,uint256)": TypedContractEvent<
      TaskRefundedEvent.InputTuple,
      TaskRefundedEvent.OutputTuple,
      TaskRefundedEvent.OutputObject
    >;
    TaskRefunded: TypedContractEvent<
      TaskRefundedEvent.InputTuple,
      TaskRefundedEvent.OutputTuple,
      TaskRefundedEvent.OutputObject
    >;

    "TaskReleased(bytes32,address,uint256)": TypedContractEvent<
      TaskReleasedEvent.InputTuple,
      TaskReleasedEvent.OutputTuple,
      TaskReleasedEvent.OutputObject
    >;
    TaskReleased: TypedContractEvent<
      TaskReleasedEvent.InputTuple,
      TaskReleasedEvent.OutputTuple,
      TaskReleasedEvent.OutputObject
    >;
  };
}
