/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace WorkspaceRegistry {
  export type MemberStruct = {
    memberAddress: AddressLike;
    joinedAt: BigNumberish;
    role: BigNumberish;
    exists: boolean;
  };

  export type MemberStructOutput = [
    memberAddress: string,
    joinedAt: bigint,
    role: bigint,
    exists: boolean
  ] & {
    memberAddress: string;
    joinedAt: bigint;
    role: bigint;
    exists: boolean;
  };

  export type WorkspaceInfoStruct = {
    id: BytesLike;
    name: string;
    description: string;
    owner: AddressLike;
    createdAt: BigNumberish;
    isPublic: boolean;
    memberCount: BigNumberish;
  };

  export type WorkspaceInfoStructOutput = [
    id: string,
    name: string,
    description: string,
    owner: string,
    createdAt: bigint,
    isPublic: boolean,
    memberCount: bigint
  ] & {
    id: string;
    name: string;
    description: string;
    owner: string;
    createdAt: bigint;
    isPublic: boolean;
    memberCount: bigint;
  };
}

export interface WorkspaceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createWorkspace"
      | "getMember"
      | "getPublicWorkspaces"
      | "getUserWorkspaces"
      | "getWorkspace"
      | "getWorkspaceMembers"
      | "isMember"
      | "joinPublicWorkspace"
      | "joinWithInviteCode"
      | "leaveWorkspace"
      | "owner"
      | "removeMember"
      | "renounceOwnership"
      | "setInviteCode"
      | "setMemberRole"
      | "transferOwnership(bytes32,address)"
      | "transferOwnership(address)"
      | "updateWorkspace"
      | "verifyInviteCode"
      | "workspaceCount"
      | "workspaceMembers"
      | "workspaces"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InviteCodeUpdated"
      | "MemberJoined"
      | "MemberLeft"
      | "MemberRoleChanged"
      | "OwnershipTransferred"
      | "WorkspaceCreated"
      | "WorkspaceUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createWorkspace",
    values: [string, string, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMember",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicWorkspaces",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserWorkspaces",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkspace",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkspaceMembers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMember",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinPublicWorkspace",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinWithInviteCode",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "leaveWorkspace",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeMember",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setInviteCode",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMemberRole",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership(bytes32,address)",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWorkspace",
    values: [BytesLike, string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyInviteCode",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "workspaceCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "workspaceMembers",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "workspaces",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createWorkspace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPublicWorkspaces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserWorkspaces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkspace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkspaceMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "joinPublicWorkspace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "joinWithInviteCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leaveWorkspace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInviteCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMemberRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership(bytes32,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWorkspace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyInviteCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "workspaceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "workspaceMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "workspaces", data: BytesLike): Result;
}

export namespace InviteCodeUpdatedEvent {
  export type InputTuple = [workspaceId: BytesLike];
  export type OutputTuple = [workspaceId: string];
  export interface OutputObject {
    workspaceId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberJoinedEvent {
  export type InputTuple = [
    workspaceId: BytesLike,
    member: AddressLike,
    role: BigNumberish
  ];
  export type OutputTuple = [workspaceId: string, member: string, role: bigint];
  export interface OutputObject {
    workspaceId: string;
    member: string;
    role: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberLeftEvent {
  export type InputTuple = [workspaceId: BytesLike, member: AddressLike];
  export type OutputTuple = [workspaceId: string, member: string];
  export interface OutputObject {
    workspaceId: string;
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberRoleChangedEvent {
  export type InputTuple = [
    workspaceId: BytesLike,
    member: AddressLike,
    newRole: BigNumberish
  ];
  export type OutputTuple = [
    workspaceId: string,
    member: string,
    newRole: bigint
  ];
  export interface OutputObject {
    workspaceId: string;
    member: string;
    newRole: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkspaceCreatedEvent {
  export type InputTuple = [
    workspaceId: BytesLike,
    name: string,
    owner: AddressLike,
    isPublic: boolean
  ];
  export type OutputTuple = [
    workspaceId: string,
    name: string,
    owner: string,
    isPublic: boolean
  ];
  export interface OutputObject {
    workspaceId: string;
    name: string;
    owner: string;
    isPublic: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkspaceUpdatedEvent {
  export type InputTuple = [
    workspaceId: BytesLike,
    name: string,
    description: string
  ];
  export type OutputTuple = [
    workspaceId: string,
    name: string,
    description: string
  ];
  export interface OutputObject {
    workspaceId: string;
    name: string;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WorkspaceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): WorkspaceRegistry;
  waitForDeployment(): Promise<this>;

  interface: WorkspaceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createWorkspace: TypedContractMethod<
    [name: string, description: string, isPublic: boolean, inviteCode: string],
    [string],
    "nonpayable"
  >;

  getMember: TypedContractMethod<
    [workspaceId: BytesLike, member: AddressLike],
    [WorkspaceRegistry.MemberStructOutput],
    "view"
  >;

  getPublicWorkspaces: TypedContractMethod<
    [],
    [WorkspaceRegistry.WorkspaceInfoStructOutput[]],
    "view"
  >;

  getUserWorkspaces: TypedContractMethod<
    [user: AddressLike],
    [string[]],
    "view"
  >;

  getWorkspace: TypedContractMethod<
    [workspaceId: BytesLike],
    [WorkspaceRegistry.WorkspaceInfoStructOutput],
    "view"
  >;

  getWorkspaceMembers: TypedContractMethod<
    [workspaceId: BytesLike],
    [string[]],
    "view"
  >;

  isMember: TypedContractMethod<
    [workspaceId: BytesLike, user: AddressLike],
    [boolean],
    "view"
  >;

  joinPublicWorkspace: TypedContractMethod<
    [workspaceId: BytesLike],
    [void],
    "nonpayable"
  >;

  joinWithInviteCode: TypedContractMethod<
    [workspaceId: BytesLike, inviteCode: string],
    [void],
    "nonpayable"
  >;

  leaveWorkspace: TypedContractMethod<
    [workspaceId: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeMember: TypedContractMethod<
    [workspaceId: BytesLike, member: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setInviteCode: TypedContractMethod<
    [workspaceId: BytesLike, newInviteCode: string],
    [void],
    "nonpayable"
  >;

  setMemberRole: TypedContractMethod<
    [workspaceId: BytesLike, member: AddressLike, newRole: BigNumberish],
    [void],
    "nonpayable"
  >;

  "transferOwnership(bytes32,address)": TypedContractMethod<
    [workspaceId: BytesLike, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  "transferOwnership(address)": TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateWorkspace: TypedContractMethod<
    [
      workspaceId: BytesLike,
      name: string,
      description: string,
      isPublic: boolean
    ],
    [void],
    "nonpayable"
  >;

  verifyInviteCode: TypedContractMethod<
    [workspaceId: BytesLike, inviteCode: string],
    [boolean],
    "view"
  >;

  workspaceCount: TypedContractMethod<[], [bigint], "view">;

  workspaceMembers: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        memberAddress: string;
        joinedAt: bigint;
        role: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  workspaces: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        string,
        bigint,
        boolean
      ] & {
        id: string;
        name: string;
        description: string;
        owner: string;
        createdAt: bigint;
        isPublic: boolean;
        inviteCodeHash: string;
        memberCount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createWorkspace"
  ): TypedContractMethod<
    [name: string, description: string, isPublic: boolean, inviteCode: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMember"
  ): TypedContractMethod<
    [workspaceId: BytesLike, member: AddressLike],
    [WorkspaceRegistry.MemberStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPublicWorkspaces"
  ): TypedContractMethod<
    [],
    [WorkspaceRegistry.WorkspaceInfoStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserWorkspaces"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getWorkspace"
  ): TypedContractMethod<
    [workspaceId: BytesLike],
    [WorkspaceRegistry.WorkspaceInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWorkspaceMembers"
  ): TypedContractMethod<[workspaceId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isMember"
  ): TypedContractMethod<
    [workspaceId: BytesLike, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinPublicWorkspace"
  ): TypedContractMethod<[workspaceId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "joinWithInviteCode"
  ): TypedContractMethod<
    [workspaceId: BytesLike, inviteCode: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "leaveWorkspace"
  ): TypedContractMethod<[workspaceId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeMember"
  ): TypedContractMethod<
    [workspaceId: BytesLike, member: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setInviteCode"
  ): TypedContractMethod<
    [workspaceId: BytesLike, newInviteCode: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMemberRole"
  ): TypedContractMethod<
    [workspaceId: BytesLike, member: AddressLike, newRole: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership(bytes32,address)"
  ): TypedContractMethod<
    [workspaceId: BytesLike, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership(address)"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateWorkspace"
  ): TypedContractMethod<
    [
      workspaceId: BytesLike,
      name: string,
      description: string,
      isPublic: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyInviteCode"
  ): TypedContractMethod<
    [workspaceId: BytesLike, inviteCode: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "workspaceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "workspaceMembers"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        memberAddress: string;
        joinedAt: bigint;
        role: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "workspaces"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        string,
        bigint,
        boolean
      ] & {
        id: string;
        name: string;
        description: string;
        owner: string;
        createdAt: bigint;
        isPublic: boolean;
        inviteCodeHash: string;
        memberCount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "InviteCodeUpdated"
  ): TypedContractEvent<
    InviteCodeUpdatedEvent.InputTuple,
    InviteCodeUpdatedEvent.OutputTuple,
    InviteCodeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MemberJoined"
  ): TypedContractEvent<
    MemberJoinedEvent.InputTuple,
    MemberJoinedEvent.OutputTuple,
    MemberJoinedEvent.OutputObject
  >;
  getEvent(
    key: "MemberLeft"
  ): TypedContractEvent<
    MemberLeftEvent.InputTuple,
    MemberLeftEvent.OutputTuple,
    MemberLeftEvent.OutputObject
  >;
  getEvent(
    key: "MemberRoleChanged"
  ): TypedContractEvent<
    MemberRoleChangedEvent.InputTuple,
    MemberRoleChangedEvent.OutputTuple,
    MemberRoleChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WorkspaceCreated"
  ): TypedContractEvent<
    WorkspaceCreatedEvent.InputTuple,
    WorkspaceCreatedEvent.OutputTuple,
    WorkspaceCreatedEvent.OutputObject
  >;
  getEvent(
    key: "WorkspaceUpdated"
  ): TypedContractEvent<
    WorkspaceUpdatedEvent.InputTuple,
    WorkspaceUpdatedEvent.OutputTuple,
    WorkspaceUpdatedEvent.OutputObject
  >;

  filters: {
    "InviteCodeUpdated(bytes32)": TypedContractEvent<
      InviteCodeUpdatedEvent.InputTuple,
      InviteCodeUpdatedEvent.OutputTuple,
      InviteCodeUpdatedEvent.OutputObject
    >;
    InviteCodeUpdated: TypedContractEvent<
      InviteCodeUpdatedEvent.InputTuple,
      InviteCodeUpdatedEvent.OutputTuple,
      InviteCodeUpdatedEvent.OutputObject
    >;

    "MemberJoined(bytes32,address,uint8)": TypedContractEvent<
      MemberJoinedEvent.InputTuple,
      MemberJoinedEvent.OutputTuple,
      MemberJoinedEvent.OutputObject
    >;
    MemberJoined: TypedContractEvent<
      MemberJoinedEvent.InputTuple,
      MemberJoinedEvent.OutputTuple,
      MemberJoinedEvent.OutputObject
    >;

    "MemberLeft(bytes32,address)": TypedContractEvent<
      MemberLeftEvent.InputTuple,
      MemberLeftEvent.OutputTuple,
      MemberLeftEvent.OutputObject
    >;
    MemberLeft: TypedContractEvent<
      MemberLeftEvent.InputTuple,
      MemberLeftEvent.OutputTuple,
      MemberLeftEvent.OutputObject
    >;

    "MemberRoleChanged(bytes32,address,uint8)": TypedContractEvent<
      MemberRoleChangedEvent.InputTuple,
      MemberRoleChangedEvent.OutputTuple,
      MemberRoleChangedEvent.OutputObject
    >;
    MemberRoleChanged: TypedContractEvent<
      MemberRoleChangedEvent.InputTuple,
      MemberRoleChangedEvent.OutputTuple,
      MemberRoleChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WorkspaceCreated(bytes32,string,address,bool)": TypedContractEvent<
      WorkspaceCreatedEvent.InputTuple,
      WorkspaceCreatedEvent.OutputTuple,
      WorkspaceCreatedEvent.OutputObject
    >;
    WorkspaceCreated: TypedContractEvent<
      WorkspaceCreatedEvent.InputTuple,
      WorkspaceCreatedEvent.OutputTuple,
      WorkspaceCreatedEvent.OutputObject
    >;

    "WorkspaceUpdated(bytes32,string,string)": TypedContractEvent<
      WorkspaceUpdatedEvent.InputTuple,
      WorkspaceUpdatedEvent.OutputTuple,
      WorkspaceUpdatedEvent.OutputObject
    >;
    WorkspaceUpdated: TypedContractEvent<
      WorkspaceUpdatedEvent.InputTuple,
      WorkspaceUpdatedEvent.OutputTuple,
      WorkspaceUpdatedEvent.OutputObject
    >;
  };
}
