/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAgreementRegistry } from "./IAgreementRegistry";
export type { IIPRegistry } from "./IIPRegistry";
export type { INodeRegistry } from "./INodeRegistry";
export type { IWorkspaceRegistry } from "./IWorkspaceRegistry";
