/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface INodeRegistryInterface extends Interface {
  getFunction(nameOrSignature: "getNode" | "isNodeEligible"): FunctionFragment;

  encodeFunctionData(functionFragment: "getNode", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isNodeEligible",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getNode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isNodeEligible",
    data: BytesLike
  ): Result;
}

export interface INodeRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): INodeRegistry;
  waitForDeployment(): Promise<this>;

  interface: INodeRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getNode: TypedContractMethod<
    [nodeId: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        owner: string;
        stakedAmount: bigint;
        pendingRewards: bigint;
        totalEarned: bigint;
        totalComputeSeconds: bigint;
        reputation: bigint;
        registeredAt: bigint;
        lastActiveAt: bigint;
        isActive: boolean;
        isSlashed: boolean;
      }
    ],
    "view"
  >;

  isNodeEligible: TypedContractMethod<[nodeId: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getNode"
  ): TypedContractMethod<
    [nodeId: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        owner: string;
        stakedAmount: bigint;
        pendingRewards: bigint;
        totalEarned: bigint;
        totalComputeSeconds: bigint;
        reputation: bigint;
        registeredAt: bigint;
        lastActiveAt: bigint;
        isActive: boolean;
        isSlashed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isNodeEligible"
  ): TypedContractMethod<[nodeId: BytesLike], [boolean], "view">;

  filters: {};
}
