/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IWorkspaceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getMember" | "getWorkspace" | "isMember"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMember",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkspace",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMember",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWorkspace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
}

export interface IWorkspaceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IWorkspaceRegistry;
  waitForDeployment(): Promise<this>;

  interface: IWorkspaceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMember: TypedContractMethod<
    [workspaceId: BytesLike, member: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        memberAddress: string;
        joinedAt: bigint;
        role: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getWorkspace: TypedContractMethod<
    [workspaceId: BytesLike],
    [
      [string, string, string, string, bigint, boolean, bigint] & {
        id: string;
        name: string;
        description: string;
        owner: string;
        createdAt: bigint;
        isPublic: boolean;
        memberCount: bigint;
      }
    ],
    "view"
  >;

  isMember: TypedContractMethod<
    [workspaceId: BytesLike, user: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMember"
  ): TypedContractMethod<
    [workspaceId: BytesLike, member: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        memberAddress: string;
        joinedAt: bigint;
        role: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWorkspace"
  ): TypedContractMethod<
    [workspaceId: BytesLike],
    [
      [string, string, string, string, bigint, boolean, bigint] & {
        id: string;
        name: string;
        description: string;
        owner: string;
        createdAt: bigint;
        isPublic: boolean;
        memberCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMember"
  ): TypedContractMethod<
    [workspaceId: BytesLike, user: AddressLike],
    [boolean],
    "view"
  >;

  filters: {};
}
